import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import SessionWrapper from "../components/SessionWrapper";
import { cn } from "@/lib/utils";
import ReactQueryProvider from "../utils/providers";
import { NextIntlClientProvider } from "next-intl";

import { useToast } from "@/components/ui/use-toast";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as SonnerToaster } from "sonner";
import "leaflet/dist/leaflet.css";
import L from "leaflet";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang="en" >
        <body
          className=" font-sans text-black"
        >
          <useToast />
          <Toaster />
          <SonnerToaster
            richColors
            toastOptions={{
              classNames: {
                title: "font-bold",
              },
            }}
          />
          <ReactQueryProvider>
              {children}
          </ReactQueryProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
